Number 1 task

In [16]:
import numpy as n
array = n.arange(10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


Number 2

In [17]:
import numpy as n
arr= n.random.randint(100,size=(4,4))
print(arr)


[[36 64 93 65]
 [73 66 87 68]
 [74 18  4 45]
 [29 63 82 20]]


Number 3

In [18]:
import numpy as n
arr = n.arange(20).reshape(4, 5)

Number **4**

In [19]:
import numpy as n
arr= n.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Number 5

In [20]:
import numpy as n
arr= n.random.rand(2,3)
print(arr)

[[0.00639781 0.5654917  0.20102758]
 [0.69936716 0.55464776 0.44128805]]


Number 6

In [21]:
import numpy as n
arr= n.random.rand(3,2)
print(arr)

[[0.85011504 0.89872005]
 [0.59822727 0.86609902]
 [0.65190835 0.63320366]]


Number *7*

In [22]:
import numpy as n
x = n.random.rand(5,5)
print(x)

[[0.22055277 0.78038478 0.4595462  0.31563352 0.40768129]
 [0.44875839 0.24489657 0.93212364 0.58245902 0.0118265 ]
 [0.64041609 0.54815483 0.37593443 0.40627021 0.01034664]
 [0.14790001 0.37951625 0.45331654 0.82821628 0.71737568]
 [0.93901961 0.73346749 0.85243491 0.23238627 0.27285623]]


Number 8

In [23]:
import numpy as n
arr = n.arange(1, 13)
reshaped_arr = arr.reshape(3, 4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Number 9


In [24]:
import numpy as n
array_2d = n.array([[1, 2, 3], [4, 5, 6]])
array_1d = array_2d.reshape(-1)
print(array_1d)
array_1d = array_2d.flatten()

[1 2 3 4 5 6]


Number 10

In [25]:
import numpy as n

array_1d = n.arange(9)
print(array_1d)

array_3x3 = array_1d.reshape((3, 3))
print(array_3x3)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
